export const CREATE_ORDERS_REQUEST = 'CREATE_ORDERS_REQUEST'
export const CREATE_ORDERS_SUCCESS = 'CREATE_ORDERS_SUCCESS'
export const CREATE_ORDERS_FAIL = 'CREATE_ORDER_FAIL'

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL'